name: Mod Request
description: Request a mod
title: "[MOD] <insert mod name here>"
labels: ["mod request"]
body:
  - type: markdown
    attributes:
      value: "## Don't forget to change the title right above!"
  - type: input
    id: link
    attributes:
      label: Mod Link
      description: "Provide a link to the mod you want to add. Don't give a direct download link, give the page of the mod on Modrinth (preferred) or Curseforge."
      placeholder: ex. https://modrinth.com/mod/sodium
    validations:
      required: true
  - type: textarea
    id: mod_info
    attributes:
      label: Info about the mod
      description: "Add here info about the mod: conflicts, dependencies and config files."
      placeholder: "ex. depends on fabric api, incompatible with optifabric, config file: sodium-options.json"
    validations:
      required: true
  - type: textarea
    id: additional_info
    attributes:
      label: Additional Info
      description: Any other info that you would like to add.
